export const ROUTES = {
  landing: "/",
  privacy: "/privacy",
  terms: "/terms",
  auth: "/auth",
  dashboard: "/dashboard",
  profile: "/settings",
  analytics: "/analytics",
  settings: "/settings",
  questionBanks: "/question-banks",
  questionBank: (id: string) => `/question-banks/${id}`,
  tests: "/tests",
  createTest: "/tests/create",
  test: (id: string) => `/tests/${id}`,
  attemptTest: (id: string) => `/tests/${id}/attempt`,
  results: "/results",
  attemptResult: (id: string) => `/attempts/${id}/result`,
  practice: "/practice",
  practiceConfig: "/practice/config",
};
