/** Central route registry — never hard-code paths in components. */
export const ROUTES = {
  landing: "/",
  auth: "/auth",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  questionBanks: "/question-banks",
  questionBank: (id: string) => `/question-banks/${id}`,
  importQuestions: (id: string) => `/question-banks/${id}/import`,
  tests: "/tests",
  createTest: "/tests/create",
  test: (id: string) => `/tests/${id}`,
  attemptTest: (id: string) => `/tests/${id}/attempt`,
  attemptResult: (attemptId: string) => `/attempts/${attemptId}/result`,
  practice: "/practice",
  practiceConfig: "/practice/config",
  practiceSession: (id: string) => `/practice/${id}`,
  analytics: "/analytics",
  settings: "/settings",
  profile: "/profile",
} as const;
