/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAttemptsIndexRouteImport } from './routes/_authenticated/attempts/index'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice/index'
import { Route as AuthenticatedPracticeConfigRouteImport } from './routes/_authenticated/practice/config'
import { Route as AuthenticatedQuestionBanksIndexRouteImport } from './routes/_authenticated/question-banks/index'
import { Route as AuthenticatedTestsIndexRouteImport } from './routes/_authenticated/tests/index'
import { Route as AuthenticatedTestsTestIdRouteImport } from './routes/_authenticated/tests/$testId'
import { Route as AuthenticatedTestsCreateRouteImport } from './routes/_authenticated/tests/create'
import { Route as AuthenticatedAttemptsAttemptIdIndexRouteImport } from './routes/_authenticated/attempts/$attemptId.index'
import { Route as AuthenticatedAttemptsAttemptIdResultRouteImport } from './routes/_authenticated/attempts/$attemptId.result'
import { Route as AuthenticatedQuestionBanksBankIdIndexRouteImport } from './routes/_authenticated/question-banks/$bankId.index'
import { Route as AuthenticatedQuestionBanksBankIdImportRouteImport } from './routes/_authenticated/question-banks/$bankId.import'
import { Route as AuthenticatedTestsTestIdAttemptRouteImport } from './routes/_authenticated/tests/$testId.attempt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttemptsIndexRoute =
  AuthenticatedAttemptsIndexRouteImport.update({
    id: '/attempts/',
    path: '/attempts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeConfigRoute =
  AuthenticatedPracticeConfigRouteImport.update({
    id: '/practice/config',
    path: '/practice/config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBanksIndexRoute =
  AuthenticatedQuestionBanksIndexRouteImport.update({
    id: '/question-banks/',
    path: '/question-banks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsIndexRoute = AuthenticatedTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsTestIdRoute =
  AuthenticatedTestsTestIdRouteImport.update({
    id: '/tests/$testId',
    path: '/tests/$testId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsCreateRoute =
  AuthenticatedTestsCreateRouteImport.update({
    id: '/tests/create',
    path: '/tests/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttemptsAttemptIdIndexRoute =
  AuthenticatedAttemptsAttemptIdIndexRouteImport.update({
    id: '/attempts/$attemptId/',
    path: '/attempts/$attemptId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttemptsAttemptIdResultRoute =
  AuthenticatedAttemptsAttemptIdResultRouteImport.update({
    id: '/attempts/$attemptId/result',
    path: '/attempts/$attemptId/result',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBanksBankIdIndexRoute =
  AuthenticatedQuestionBanksBankIdIndexRouteImport.update({
    id: '/question-banks/$bankId/',
    path: '/question-banks/$bankId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBanksBankIdImportRoute =
  AuthenticatedQuestionBanksBankIdImportRouteImport.update({
    id: '/question-banks/$bankId/import',
    path: '/question-banks/$bankId/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsTestIdAttemptRoute =
  AuthenticatedTestsTestIdAttemptRouteImport.update({
    id: '/attempt',
    path: '/attempt',
    getParentRoute: () => AuthenticatedTestsTestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/practice/config': typeof AuthenticatedPracticeConfigRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRouteWithChildren
  '/tests/create': typeof AuthenticatedTestsCreateRoute
  '/attempts/': typeof AuthenticatedAttemptsIndexRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/question-banks/': typeof AuthenticatedQuestionBanksIndexRoute
  '/tests/': typeof AuthenticatedTestsIndexRoute
  '/attempts/$attemptId/result': typeof AuthenticatedAttemptsAttemptIdResultRoute
  '/question-banks/$bankId/import': typeof AuthenticatedQuestionBanksBankIdImportRoute
  '/tests/$testId/attempt': typeof AuthenticatedTestsTestIdAttemptRoute
  '/attempts/$attemptId/': typeof AuthenticatedAttemptsAttemptIdIndexRoute
  '/question-banks/$bankId/': typeof AuthenticatedQuestionBanksBankIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/results': typeof AuthenticatedResultsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/practice/config': typeof AuthenticatedPracticeConfigRoute
  '/tests/$testId': typeof AuthenticatedTestsTestIdRouteWithChildren
  '/tests/create': typeof AuthenticatedTestsCreateRoute
  '/attempts': typeof AuthenticatedAttemptsIndexRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/question-banks': typeof AuthenticatedQuestionBanksIndexRoute
  '/tests': typeof AuthenticatedTestsIndexRoute
  '/attempts/$attemptId/result': typeof AuthenticatedAttemptsAttemptIdResultRoute
  '/question-banks/$bankId/import': typeof AuthenticatedQuestionBanksBankIdImportRoute
  '/tests/$testId/attempt': typeof AuthenticatedTestsTestIdAttemptRoute
  '/attempts/$attemptId': typeof AuthenticatedAttemptsAttemptIdIndexRoute
  '/question-banks/$bankId': typeof AuthenticatedQuestionBanksBankIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/practice/config': typeof AuthenticatedPracticeConfigRoute
  '/_authenticated/tests/$testId': typeof AuthenticatedTestsTestIdRouteWithChildren
  '/_authenticated/tests/create': typeof AuthenticatedTestsCreateRoute
  '/_authenticated/attempts/': typeof AuthenticatedAttemptsIndexRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/_authenticated/question-banks/': typeof AuthenticatedQuestionBanksIndexRoute
  '/_authenticated/tests/': typeof AuthenticatedTestsIndexRoute
  '/_authenticated/attempts/$attemptId/result': typeof AuthenticatedAttemptsAttemptIdResultRoute
  '/_authenticated/question-banks/$bankId/import': typeof AuthenticatedQuestionBanksBankIdImportRoute
  '/_authenticated/tests/$testId/attempt': typeof AuthenticatedTestsTestIdAttemptRoute
  '/_authenticated/attempts/$attemptId/': typeof AuthenticatedAttemptsAttemptIdIndexRoute
  '/_authenticated/question-banks/$bankId/': typeof AuthenticatedQuestionBanksBankIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/analytics'
    | '/dashboard'
    | '/results'
    | '/settings'
    | '/practice/config'
    | '/tests/$testId'
    | '/tests/create'
    | '/attempts/'
    | '/practice/'
    | '/question-banks/'
    | '/tests/'
    | '/attempts/$attemptId/result'
    | '/question-banks/$bankId/import'
    | '/tests/$testId/attempt'
    | '/attempts/$attemptId/'
    | '/question-banks/$bankId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/analytics'
    | '/dashboard'
    | '/results'
    | '/settings'
    | '/practice/config'
    | '/tests/$testId'
    | '/tests/create'
    | '/attempts'
    | '/practice'
    | '/question-banks'
    | '/tests'
    | '/attempts/$attemptId/result'
    | '/question-banks/$bankId/import'
    | '/tests/$testId/attempt'
    | '/attempts/$attemptId'
    | '/question-banks/$bankId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/results'
    | '/_authenticated/settings'
    | '/_authenticated/practice/config'
    | '/_authenticated/tests/$testId'
    | '/_authenticated/tests/create'
    | '/_authenticated/attempts/'
    | '/_authenticated/practice/'
    | '/_authenticated/question-banks/'
    | '/_authenticated/tests/'
    | '/_authenticated/attempts/$attemptId/result'
    | '/_authenticated/question-banks/$bankId/import'
    | '/_authenticated/tests/$testId/attempt'
    | '/_authenticated/attempts/$attemptId/'
    | '/_authenticated/question-banks/$bankId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attempts/': {
      id: '/_authenticated/attempts/'
      path: '/attempts'
      fullPath: '/attempts/'
      preLoaderRoute: typeof AuthenticatedAttemptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/config': {
      id: '/_authenticated/practice/config'
      path: '/practice/config'
      fullPath: '/practice/config'
      preLoaderRoute: typeof AuthenticatedPracticeConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-banks/': {
      id: '/_authenticated/question-banks/'
      path: '/question-banks'
      fullPath: '/question-banks/'
      preLoaderRoute: typeof AuthenticatedQuestionBanksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/': {
      id: '/_authenticated/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof AuthenticatedTestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/$testId': {
      id: '/_authenticated/tests/$testId'
      path: '/tests/$testId'
      fullPath: '/tests/$testId'
      preLoaderRoute: typeof AuthenticatedTestsTestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/create': {
      id: '/_authenticated/tests/create'
      path: '/tests/create'
      fullPath: '/tests/create'
      preLoaderRoute: typeof AuthenticatedTestsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attempts/$attemptId/': {
      id: '/_authenticated/attempts/$attemptId/'
      path: '/attempts/$attemptId'
      fullPath: '/attempts/$attemptId/'
      preLoaderRoute: typeof AuthenticatedAttemptsAttemptIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attempts/$attemptId/result': {
      id: '/_authenticated/attempts/$attemptId/result'
      path: '/attempts/$attemptId/result'
      fullPath: '/attempts/$attemptId/result'
      preLoaderRoute: typeof AuthenticatedAttemptsAttemptIdResultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-banks/$bankId/': {
      id: '/_authenticated/question-banks/$bankId/'
      path: '/question-banks/$bankId'
      fullPath: '/question-banks/$bankId/'
      preLoaderRoute: typeof AuthenticatedQuestionBanksBankIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-banks/$bankId/import': {
      id: '/_authenticated/question-banks/$bankId/import'
      path: '/question-banks/$bankId/import'
      fullPath: '/question-banks/$bankId/import'
      preLoaderRoute: typeof AuthenticatedQuestionBanksBankIdImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/$testId/attempt': {
      id: '/_authenticated/tests/$testId/attempt'
      path: '/attempt'
      fullPath: '/tests/$testId/attempt'
      preLoaderRoute: typeof AuthenticatedTestsTestIdAttemptRouteImport
      parentRoute: typeof AuthenticatedTestsTestIdRoute
    }
  }
}

interface AuthenticatedTestsTestIdRouteChildren {
  AuthenticatedTestsTestIdAttemptRoute: typeof AuthenticatedTestsTestIdAttemptRoute
}

const AuthenticatedTestsTestIdRouteChildren: AuthenticatedTestsTestIdRouteChildren =
  {
    AuthenticatedTestsTestIdAttemptRoute: AuthenticatedTestsTestIdAttemptRoute,
  }

const AuthenticatedTestsTestIdRouteWithChildren =
  AuthenticatedTestsTestIdRoute._addFileChildren(
    AuthenticatedTestsTestIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedPracticeConfigRoute: typeof AuthenticatedPracticeConfigRoute
  AuthenticatedTestsTestIdRoute: typeof AuthenticatedTestsTestIdRouteWithChildren
  AuthenticatedTestsCreateRoute: typeof AuthenticatedTestsCreateRoute
  AuthenticatedAttemptsIndexRoute: typeof AuthenticatedAttemptsIndexRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
  AuthenticatedQuestionBanksIndexRoute: typeof AuthenticatedQuestionBanksIndexRoute
  AuthenticatedTestsIndexRoute: typeof AuthenticatedTestsIndexRoute
  AuthenticatedAttemptsAttemptIdResultRoute: typeof AuthenticatedAttemptsAttemptIdResultRoute
  AuthenticatedQuestionBanksBankIdImportRoute: typeof AuthenticatedQuestionBanksBankIdImportRoute
  AuthenticatedAttemptsAttemptIdIndexRoute: typeof AuthenticatedAttemptsAttemptIdIndexRoute
  AuthenticatedQuestionBanksBankIdIndexRoute: typeof AuthenticatedQuestionBanksBankIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedPracticeConfigRoute: AuthenticatedPracticeConfigRoute,
  AuthenticatedTestsTestIdRoute: AuthenticatedTestsTestIdRouteWithChildren,
  AuthenticatedTestsCreateRoute: AuthenticatedTestsCreateRoute,
  AuthenticatedAttemptsIndexRoute: AuthenticatedAttemptsIndexRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
  AuthenticatedQuestionBanksIndexRoute: AuthenticatedQuestionBanksIndexRoute,
  AuthenticatedTestsIndexRoute: AuthenticatedTestsIndexRoute,
  AuthenticatedAttemptsAttemptIdResultRoute:
    AuthenticatedAttemptsAttemptIdResultRoute,
  AuthenticatedQuestionBanksBankIdImportRoute:
    AuthenticatedQuestionBanksBankIdImportRoute,
  AuthenticatedAttemptsAttemptIdIndexRoute:
    AuthenticatedAttemptsAttemptIdIndexRoute,
  AuthenticatedQuestionBanksBankIdIndexRoute:
    AuthenticatedQuestionBanksBankIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
